In [18]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split

from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score

from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score, precision_score, recall_score
from sklearn.metrics import f1_score

In [5]:
# Load the diabetes dataset
wisconsin = datasets.load_breast_cancer()

In [6]:
wisconsin.keys()

dict_keys(['data', 'target', 'target_names', 'feature_names', 'DESCR'])

In [7]:
wisconsin.target_names #nome do objetivo

array(['malignant', 'benign'],
      dtype='<U9')

In [8]:
wisconsin.target[:40] # exibir os 40 primeiros

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0])

In [9]:
wisconsin_X = wisconsin.data

In [11]:
wisconsin_X_df = pd.DataFrame(wisconsin_X)

In [12]:
wisconsin_X_df.head()

0      1       2       3        4        5       6        7       8   \
0  17.99  10.38  122.80  1001.0  0.11840  0.27760  0.3001  0.14710  0.2419   
1  20.57  17.77  132.90  1326.0  0.08474  0.07864  0.0869  0.07017  0.1812   
2  19.69  21.25  130.00  1203.0  0.10960  0.15990  0.1974  0.12790  0.2069   
3  11.42  20.38   77.58   386.1  0.14250  0.28390  0.2414  0.10520  0.2597   
4  20.29  14.34  135.10  1297.0  0.10030  0.13280  0.1980  0.10430  0.1809   

        9    ...        20     21      22      23      24      25      26  \
0  0.07871   ...     25.38  17.33  184.60  2019.0  0.1622  0.6656  0.7119   
1  0.05667   ...     24.99  23.41  158.80  1956.0  0.1238  0.1866  0.2416   
2  0.05999   ...     23.57  25.53  152.50  1709.0  0.1444  0.4245  0.4504   
3  0.09744   ...     14.91  26.50   98.87   567.7  0.2098  0.8663  0.6869   
4  0.05883   ...     22.54  16.67  152.20  1575.0  0.1374  0.2050  0.4000   

       27      28       29  
0  0.2654  0.4601  0.11890  
1  0.1860  0.2750  0.08902  
2  0.2430  0.3613  0.08758  
3  0.2575  0.6638  0.17300  
4  0.1625  0.2364  0.07678  

[5 rows x 30 columns]

In [14]:
wisconsin_X_df.columns = list(wisconsin.feature_names)

In [15]:
wisconsin_X_df.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension           ...             worst radius  \
0                 0.07871           ...                    25.38   
1                 0.05667           ...                    24.99   
2                 0.05999           ...                    23.57   
3                 0.09744           ...                    14.91   
4                 0.05883           ...                    22.54   

   worst texture  worst perimeter  worst area  worst smoothness  \
0          17.33           184.60      2019.0            0.1622   
1          23.41           158.80      1956.0            0.1238   
2          25.53           152.50      1709.0            0.1444   
3          26.50            98.87       567.7            0.2098   
4          16.67           152.20      1575.0            0.1374   

   worst compactness  worst concavity  worst concave points  worst symmetry  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   worst fractal dimension  
0                  0.11890  
1                  0.08902  
2                  0.08758  
3                  0.17300  
4                  0.07678  

[5 rows x 30 columns]

In [16]:
y = wisconsin.target

In [17]:
X = wisconsin.data

In [19]:
X_train, X_test, y_train, y_test = train_test_split(
                                        X,
                                        y, 
                                        test_size=0.2, 
                                        random_state=1)

In [20]:
rf_model = RandomForestClassifier()

In [21]:
rf_model.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [23]:
cv_scores_rf = cross_val_score(rf_model, X_train, y_train,
                              cv=5, scoring="accuracy")

In [24]:
cv_scores_rf

array([ 0.9010989 ,  0.93406593,  0.95604396,  0.94505495,  0.97802198])

In [25]:
cv_scores_rf_mean = np.mean(cv_scores_rf)
cv_scores_rf_mean

0.94285714285714284

In [26]:
y_test_pred = rf_model.predict(X_test)

In [27]:
y_test.shape

(114,)

In [28]:
pd.crosstab(y_test, y_test_pred,
           rownames=["Actual"],
           colnames=["Predicted"])

Predicted   0   1
Actual           
0          37   5
1           0  72

In [29]:
confusion_matrix(y_test, y_test_pred)

array([[37,  5],
       [ 0, 72]])

In [30]:
accuracy_score_test = accuracy_score(y_test, y_test_pred)
accuracy_score_test

0.95614035087719296

In [31]:
precision_score_forest = precision_score(y_test, y_test_pred)
precision_score_forest

0.93506493506493504

In [33]:
recall_score_forest = recall_score(y_test, y_test_pred)
recall_score_forest

1.0

In [34]:
f1_score_forest = f1_score(y_test, y_test_pred)
f1_score_forest

0.96644295302013428

In [35]:
comparison = {"Validation": [cv_scores_rf_mean],
              "Test": [accuracy_score_test]}
pd.DataFrame(comparison, index=["Accuracy"])

Test  Validation
Accuracy  0.95614    0.942857

In [36]:
rf_model.feature_importances_

array([ 0.00949425,  0.01590297,  0.14059487,  0.01106984,  0.0095764 ,
        0.00070106,  0.11796827,  0.08970213,  0.00315957,  0.00572715,
        0.00292439,  0.00336473,  0.04749127,  0.01435328,  0.00395505,
        0.00571706,  0.00509606,  0.00049251,  0.00466983,  0.00944809,
        0.09419753,  0.01758875,  0.03415863,  0.10715569,  0.01419509,
        0.00575437,  0.03612568,  0.17512132,  0.01091047,  0.00338369])

In [38]:
imp_list = list(zip(wisconsin.feature_names,
                    rf_model.feature_importances_))
imp_df = pd.DataFrame(imp_list, columns=["Features", "Importance"])
imp_df.sort_values(by="Importance", ascending=False)

Features  Importance
27     worst concave points    0.175121
2            mean perimeter    0.140595
6            mean concavity    0.117968
23               worst area    0.107156
20             worst radius    0.094198
7       mean concave points    0.089702
12          perimeter error    0.047491
26          worst concavity    0.036126
22          worst perimeter    0.034159
21            worst texture    0.017589
1              mean texture    0.015903
13               area error    0.014353
24         worst smoothness    0.014195
3                 mean area    0.011070
28           worst symmetry    0.010910
4           mean smoothness    0.009576
0               mean radius    0.009494
19  fractal dimension error    0.009448
25        worst compactness    0.005754
9    mean fractal dimension    0.005727
15        compactness error    0.005717
16          concavity error    0.005096
18           symmetry error    0.004670
14         smoothness error    0.003955
29  worst fractal dimension    0.003384
11            texture error    0.003365
8             mean symmetry    0.003160
10             radius error    0.002924
5          mean compactness    0.000701
17     concave points error    0.000493